### ISSUE TITLE
can not install with pip

### ISSUE THREAD

**Issue by dfroger** [craftr-build/craftr#105]
$ pip install craftr-build

     Collecting craftr-build
      Could not find a version that satisfies the requirement craftr-build (from versions: 1.0.0-src)
     No matching distribution found for craftr-build

**Comment by NiklasRosenstein** [comment]
Thanks for letting me know there's a problem installing Craftr with Pip. I messed up when I published the `1.0.0` version to PyPI and it doesn't allow you to re-upload under the same version number. I'll create a `1.0.1` release that is the exact same version but the installation should work.

By the way, I welcome that you want to try out Craftr! I just want to let you know that the current development version has a lot of changes, so you might want to look into the current master branch instead of the older version on PyPI! (Here's the [Changelog](http://craftr.readthedocs.io/en/latest/changelog.html)) Otherwise you might get annoyed when you like Craftr and suddenly everything's different with the next version :)

You can install Craftr easily from the GitHub repository as well:

```
$ git clone https://github.com/craftr-build/craftr.git
$ cd craftr
$ pip install .
```

(I also suggest using `pip install -e .` to be able to update to the newest version by simply doing `git pull` from the cloned repository).

**Comment by NiklasRosenstein** [comment]
I hate PyPI :) If you still want to try out the old version, `pip install craftr-build` should now install `v1.0.3` (which is the same as `v1.0.0` but the install process should work)

**Comment by dfroger** [comment]
Hi Niklas, thank for your quick reply! 

Install from `PyPy` now works for me. (I have then another error, will open another issue for it).

Craft features and examples looks great! I'm going to try it on a `Cython` project.

**Comment by NiklasRosenstein** [comment]
> Craft features and examples looks great! I'm going to try it on a `Cython` project.

FYI there's a Cython compiler module that makes converting `.pyx` files to `.c` or `.cpp` files with Cython a bit easier. :)

http://craftr.readthedocs.io/en/latest/stl/compiler_cython.html
